### ISSUE TITLE
Introduce a way to scale the service

### ISSUE THREAD

**Issue by markunsworth** [jpetazzo/rabbitmq-on-dotcloud-ALPHA#4]
At the moment it's not possible to scale RabbitMQ using the dotcloud scale command. 

There are a few immediate issues with this:
- resolution of shortnames
- clustering doesn't work well across WAN
- the admin console will be deployed across each node which is probably unnecessary 

I wanted to start this issue as a discussion to help work out the best way to resolve these issues (if possible).

**Comment by jpetazzo** [comment]
IIRC, all nodes of a RabbitMQ cluster must connect to each other using the same port number. Unfortunately, this constraint is not feasible on dotCloud :-(

Or is there a way to have a RabbitMQ cluster with each node using different TCP ports?
